cache:
  directories:
  - projects/com.oracle.truffle.llvm.test/suites
  - projects/com.oracle.truffle.llvm.tools/tools
  - graal-jvmci-8/
sudo: required
language: java
python:
  - "2.7"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python2.7
    - gcc-4.6
    - g++-4.6
    - gfortran-4.6
    - libgmp3-dev
    - llvm-3.3
    - clang-format-3.4
    - gobjc++-4.6
    - gcc-4.6-plugin-dev
install:
  - export MX_BINARY_SUITES="jvmci"
  - gem install mdl
  - pip install astroid==1.1.0 --user `whoami`
  - pip install pylint==1.1.0 --user `whoami`
  - git clone https://github.com/graalvm/mx
  - wget -O mx/ecj.jar 'http://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.5.1-201509040015/ecj-4.5.1.jar'
  - export JDT=`pwd`/mx/ecj.jar
  - wget http://lafo.ssw.uni-linz.ac.at/sulong-deps/eclipse-jdk8-linux-x86_64.tar.gz
  - tar -xvzf eclipse-jdk8-linux-x86_64.tar.gz
  - export ECLIPSE_EXE=eclipse/eclipse
  - export DEFAULT_VM=server
  - export PATH=`pwd`/mx:$PATH
  - 'wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-linux-x64.tar.gz'
  - tar -zxf jdk-8u92-linux-x64.tar.gz
  - if [ -d graal-jvmci-8/.hg ]; then cd graal-jvmci-8/ && hg pull && hg update; else hg clone http://hg.openjdk.java.net/graal/graal-jvmci-8; fi;
  - cd graal-jvmci-8
  - mx --java-home `pwd`/../jdk1.8.0_92/ build
  - export JAVA_HOME=$(mx --java-home `pwd`/../jdk1.8.0_92 jdkhome)
  - cd ..
script:
  - $TEST_COMMAND
branches:
  only:
    - master
env:
  - TEST_COMMAND='mx su-clangformatcheck && mx eclipseformat --primary && mx su-mdlcheck && mx su-gitlogcheck && mx pylint && mx checkstyle && mx checkoverlap && mx canonicalizeprojects'
  - TEST_COMMAND='mx su-travis1'
  - TEST_COMMAND='mx su-travis2'
  - TEST_COMMAND='mx su-travis3'
after_failure:
  - find . -iname "*.log" -print0 | xargs -0 cat
