language: java
os:
  - linux
  - osx
python:
  - "2.7"
jdk:
  - oraclejdk8
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:mercurial-ppa/releases	; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:fkrull/deadsnakes		; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y update									; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python2.7							; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install mercurial							; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc-4.6							; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gcc-4.6-plugin-dev					; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gobjc++-4.6						; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install g++-4.6							; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install gfortran-4.6						; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgmp3-dev						; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install llvm-3.3							; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install astroid==1.1.0							; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install pylint==1.1.0							; fi
  - pylint --version
  - hg --version
  - git clone https://github.com/graalvm/mx
  - wget http://ftp.halifax.rwth-aachen.de/eclipse//eclipse/downloads/drops4/R-4.5.1-201509040015/ecj-4.5.1.jar
  - mv ecj-4.5.1.jar mx/ecj.jar
  - export JDT=`pwd`/mx/ecj.jar
  - wget https://lafo.ssw.uni-linz.ac.at/slavefiles/gate/eclipse-jdk8-linux-x86_64.tar.gz
  - tar -xvzf eclipse-jdk8-linux-x86_64.tar.gz
  - export ECLIPSE_EXE=eclipse/eclipse
  - export DEFAULT_VM=server
script:
  - $TEST_COMMAND
branches:
  only:
    - master
env:
  - TEST_COMMAND='mx/mx pylint'
  - TEST_COMMAND='mx/mx checkstyle'
  - TEST_COMMAND='mx/mx checkoverlap'
  - TEST_COMMAND='mx/mx canonicalizeprojects'
  - TEST_COMMAND='mx/mx su-travis1'
  - TEST_COMMAND='mx/mx su-travis2'
after_failure:
  - find . -iname "*.log" -print0 | xargs -0 cat
matrix:
  allow_failures:
    - os: osx
