language: java
python:
  - "2.7"
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - python-pip
      - python-virtualenv
      - oracle-java8-installer
      - build-essential
      - wget
      - mercurial

# Use Trusty to get enough RAM
sudo: required
dist: trusty

env:
  global:
    - DEFAULT_VM="jvmci"
before_install:
  - virtualenv venv
  - source venv/bin/activate
  - pip install astroid==1.1.0
  - pip install pylint==1.1.0
  - sudo add-apt-repository -y ppa:mercurial-ppa/releases
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get -y update
  - sudo apt-get -y install python2.7
  - sudo apt-get -y install mercurial
  - sudo apt-get -y install gcc-4.6
  - sudo apt-get -y install gobjc++-4.6
  - sudo apt-get -y install g++-4.6
  - sudo apt-get -y install gfortran-4.6
install:
  - export MX_PATH=$TRAVIS_BUILD_DIR/../mx
  - git clone https://github.com/graalvm/mx.git $MX_PATH
  - export PATH=$MX_PATH/../mx:$PATH
  - export JDT=$MX_PATH/ecj.jar
  - wget http://ftp.halifax.rwth-aachen.de/eclipse//eclipse/downloads/drops4/R-4.5.1-201509040015/ecj-4.5.1.jar -O $JDT
  - export ECLIPSE_TAR=$TRAVIS_BUILD_DIR/../eclipse.tar.gz
  - wget https://lafo.ssw.uni-linz.ac.at/slavefiles/gate/eclipse-jdk8-linux-x86_64.tar.gz -O $ECLIPSE_TAR
  - tar -C $TRAVIS_BUILD_DIR/.. -xf $ECLIPSE_TAR
  - export ECLIPSE_EXE=$TRAVIS_BUILD_DIR/../eclipse/eclipse
script:
  - mx --strict-compliance gate --strict-mode
after_failure:
  - cat $TRAVIS_BUILD_DIR/jvmci/client-product.log
  - cat $TRAVIS_BUILD_DIR/jvmci/server-fastdebug.log
  - cat $TRAVIS_BUILD_DIR/jvmci/server-nojvmci-product.log
  - cat $TRAVIS_BUILD_DIR/jvmci/jvmci-fastdebug.log
  - cat $TRAVIS_BUILD_DIR/jvmci/client-fastdebug.log
  - cat $TRAVIS_BUILD_DIR/jvmci/jvmci-product.log
  - cat $TRAVIS_BUILD_DIR/jvmci/server-nojvmci-optimized.log
  - cat $TRAVIS_BUILD_DIR/jvmci/server-product.log
  - cat hs_err*
